# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (https://username.github.io) then use these settings:
url: "https://teck.camp"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Welcome to Teck Camp

# Short description of your site
description:  Unlocking the tech wilderness

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  #About Me: "aboutme"
  #Resources:
    #- Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    #- Learn markdown: "http://www.markdowntutorial.com/"
    #- GitHub Pages: "https://pages.github.com/"
    # - Photos: "https://meetup-mates.com/photos/"
  #Home: "https://teck.camp/"
  The Team: "https://teck.camp/meet-the-team/"
  Register: "https://teck.camp/register/"
  Our Partners: "https://teck.camp/our-partners/"
  Community blog: "https://tecknuovo.com/category/community-hub/?utm_source=tc&utm_medium=website&utm_campaign=crossover"
  #Twitter: "https://meetup-mates.com/mm-twitter"
  #Linkedin: "https://www.linkedin.com/showcase/meetupmates"
  Code of Conduct & Values: "https://teck.camp/code-conduct-values/"
  Privacy Notice: "https://teck.camp/privacy/"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: "/img/Teck%20Camp%20logo.png"
favicon: "/img/TC_favicon.png"

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#C7DB89"
#f3c643
navbar-text-col: "#0f2026"
navbar-children-col: "#F5F5F5"
page-col: "#EEF4DA"
link-col: "#EF5445"
hover-col: "#0f2026"
footer-col: "#C7DB89"
footer-text-col: "#0f2026"
footer-link-col: "#EF5445"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Teck Camp Team

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: "teckcamp@tecknuovo.com"
  #facebook: daattali
  github: teckcamp
  twitter: teckcamp
#  reddit: yourname
#  google-plus: +DeanAttali
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: false
  google: false
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "www.teck.camp"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-137048208-1"

# Google Tag Manager ID
gtm: "GTM-THQJV4G"

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

# matomo:
# site_id: "9"
# uri: "demo.wiki.pro"
# opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
# disqus: ""

# To use Facebook Comments, fill in a Facebook App ID
# fb_comment_id: ""

# Staticman support
staticman:
  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
  branch     : # eg. "master" If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : # URL of your own deployment (with trailing slash) (will fallback to a public GitLab instance)
  reCaptcha:
    # reCaptcha for Staticman (OPTIONAL)
    # If you use reCaptcha, you must also set these parameters in staticman.yml
    siteKey  : # Use your own site key, you need to apply for one on Google
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/London"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-twitter-plugin

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
